### PR TITLE
Added image draggable attribute, removed changelog category from readme

### PR DESCRIPTION
**Pull request by Tobix3**
- Images are no longer draggable
- Removed the changelog category from readme since no longer necessary

### CODE REVIEW

**Comment by Saladoc** [comment]
What exactly is the reason for these changes? What is the draggable attribute needed for?
The changelog information will become relevant upon the next release.

**Comment by Tobix3** [comment]
At the moment, you can drag the pictures on the website.
image
 With the draggable attribute it's no longer possible. It's a little cosmetic update.

In the readme it says that you should create a file in the `_changelog` folder for a new changelog, but that's obsolete. It's done with a [js file](https://github.com/Javacord/javacord.github.io/blob/master/js/main.js#L7), so the paragraph in the readme is no longer needed. I also talked to Bastian about it via Discord before.

**Comment by Vampire** [comment]
And why should we set `draggable` to `false`?

It is not a cosmetic change, but a restricting change that prevents normal handling.
Normal behavior is to be able to drag&drop images into the address line to only see the image, onto the desktop to save it, into a graphics program to edit it, ......

The only thing the attribute changes is to try to forbid these actions which it not really does.
The browser can choose to ignore it and there are usually always other ways like right-clicking or looking at the sources or whatever.

Setting this attribute is like websites that block right-click in an attempt to prevent the user from doing "View source" while there are a dozen other ways to do it.

So I'm not sure what this change should be good for.
As far as I understood it does in no way change the look & feel of the pages, but just tries to block normal image handling.

**Comment by Tobix3** [comment]
@Vampire: It's not the intuition of the commit to restrict anything. There are many other ways to get the same result like right-clicking as you mentioned and which is even faster than dragging it into the address bar. You can even download the image directly from the right-click menu if necessary.

I don't know why people would want to edit the images of the Javacord website. Only if someone would want to use the logo for a thumbnail (of a YouTube video), that would be the only reason for me to download an image from the site. And if you still want to drag, you can just quickly open the image in a new tab and drag it. It's no big deal.

That's why I don't quite understand the "problem".

If you still don't like it, how about keeping the attribute for the logos and removing it from the other images?

**Comment by Vampire** [comment]
Well, while you cannot see the problem I have, I cannot see the problem you try to fix.
Could you explain the problem you try to fix?

Maybe I got it wrong, but does this change do anything else (only the `draggable` part I mean) besides preventing the dragging?
You say it is not the intuition of the commit to restrict anything, so I must have misunderstood the change.
What does it change, besides restricting the draggability?

> like right-clicking [...] and which is even faster than dragging it into the address bar. You can even download the image directly from the right-click menu if necessary.

I don't agree, I have much faster just dragged the image to the address bar to open it solely in a new tab and I have much faster dragged the image to the desktop or an explorer window to save it locally. In the context menu I first have to read 10+ entries to find the one that does what I could have easily done with a simple gesture very quickly.

Please don't get me wrong, I really appreciate your intention to help, I just don't understand what you try to fix with this and how it justifies the usability restriction you introduce at the same time or why you think the usability restriction is an improvement.

**Comment by Tobix3** [comment]
It's not really a problem and after this discussion I wouldn't call it improvement either. It's a change that doesn't hurt. There are a thousand other ways to get the picture anyway, so I don't call it a restriction. Personally, I don't like it when you can drag pictures like that unnecessarily.

> I have much faster just dragged the image to the address bar to open it solely in a new tab

I would say that you dragged the image quickly into the tab area. Dragging into the navigation bar needs a little more precision. Right click, move the mouse pointer a pixel and left click is very fast.

>  In the context menu I first have to read 10+ entries to find the one that does what I could have easily done with a simple gesture very quickly.

Yeah, but how often do you do that? I don't think that you do that every day but rather rarely or maybe just once. You can do a little "more work" there. (I'm referring here only to the Javacord website with its pictures)

We're not getting very far with the discussion here. I would say we let Bastian decide how to proceed.

**Comment by Vampire** [comment]
> It's a change that doesn't hurt.

It doesn't hurt you, but it hurts ppl that do drag & drop.

> There are a thousand other ways to get the picture anyway, so I don't call it a restriction.

Of course it is a restriction.
It is not a restriction to not be able to get to the image.
But it definitely is a usability restriction.

> Personally, I don't like it when you can drag pictures like that unnecessarily.

But I don't understand why.
If you personally don't like dragging images, then don't drag images, problem solved.
Why forbid everyone else to drag images?

> I would say that you dragged the image quickly into the tab area. Dragging into the navigation bar needs a little more precision.

Why? The address bar and the tab bar are - at least for Firefox - pretty equal in height. Same precision needed. If dragged to the address bar, it opens in the current tab, if dragged to the tab bar it opens in the tab dragged to if dragged to the tab bar but not to a specific tab but to empty space or between two tabs it opens in a new tab.

> Right click, move the mouse pointer a pixel and left click is very fast.

It would be very fast if there would only be one entry in the menu.
Reading entries is much slower than just dropping the image where you want it.
And it is usually more than one pixel, as it is most probably not the entry the mouse is next to when the menu opens, at least from a statistics pov.

>> In the context menu I first have to read 10+ entries to find the one that does what I could have easily done with a simple gesture very quickly.

> Yeah, but how often do you do that? I don't think that you do that every day but rather rarely or maybe just once. You can do a little "more work" there. (I'm referring here only to the Javacord website with its pictures)

Which makes it even worse to be honest.
The less often you do the action, the longer it takes you to identify the right context menu entry, while you could simply drag and drop the image to where you want it.
That is like saying "ah, why using a pen and paper, let's forbid it, people can just scratch the words into wood with their fingernails".
It would work, but it is unnecessary PITA.
It might not be a big issue whether you can drag or not actually, but I just don't see any sense in doing a pointless change that puts restrictions on established usage patterns for no reason at all but personal dislike.

> We're not getting very far with the discussion here. I would say we let Bastian decide how to proceed.

Agreed.

**Review by Vampire — CHANGES_REQUESTED** [review]
Don't like it, sorry. :-(

**Comment by Bastian** [comment]
I have to agree with Vampire: There's no benefit in making images "undraggable".

You are correct that the "changelog" paragraph in the readme is obsolte tho.

**Pull request closed without merging**
